app_wagntails/urls.py
from django.conf.urls import include
from django.urls import path
from django.conf.urls import handler404, handler400, handler403, handler500

from . import views

urlpatterns = [
    path('register/', views.registerPage, name="register"),
    path('loginOwner/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),

    path('', views.home, name="home"),
    path('baseLogin/', views.baseLogin, name="baseLogin"),
    path('owner/', views.ownerPage, name="owner-page"),

    path('account/', views.accountSettings, name="account"),
    path('ownerDashboard/', views.ownerDashboard, name="ownerDashboard"),
    path('volunteerDashboard/', views.volunteerDashboard,
         name="volunteerDashboard"),

    path('dogs/<str:pk>/', views.dogs, name='dogs'),
    path('owner/<str:pk_test>/', views.owner, name="owner"),
    path('viewVolunteers/<str:pk>/', views.volunteers, name="volunteers"),

    path('create_dog/<str:pk>/', views.createDog, name="create_dog"),
    path('update_dog/<str:pk>/', views.updateDog, name="update_dog"),
    path('delete_dog/<str:pk>/', views.deleteDog, name="delete_dog"),
    path('addlocation/<str:pk>/', views.addDateLocation, name="date-location"),
    path('updatelocation/<str:pk>/<str:pk_test>',
         views.updateDateLocation, name="update-location"),
    path('deletelocation/<str:pk>/<str:pk_test>',
         views.deleteDateLocation, name="delete-location"),
    path('addplaydate/<str:pk>/', views.addPlayDate, name="play-date"),
    path('error/<str:pk>/', views.error, name="error"),

    ########### Volunteer Related ##########
    path('registerVolunteer/', views.registerVolunteerPage,
         name="registerVolunteer"),
    path('loginVolunteer/', views.loginVolunteerPage, name="loginVolunteer"),
    path('logoutVolunteer/', views.logoutVolunteerUser, name="logoutVolunteer"),
    path('homeVolunteer/', views.homeVolunteer, name="homeVolunteer"),
    path('accountVolunteer/', views.accountSettingsVolunteer,
         name="accountVolunteer"),
    path('volunteer/', views.volunteerPage, name="volunteer-page"),
    path('volunteer/<str:pk_test>/', views.volunteer, name="volunteer"),
    path('associateVolunteer/<str:pk>/',
         views.associateVolunteer, name="associateVolunteer"),

    ########### Chat Related ##########
    path('chat/<str:pk>/', views.chat_view, name='chats'),
    path('chatMessage/<str:sender>/<str:receiver>/<str:pk>/',
         views.message_view, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>/',
         views.message_list, name='message-detail'),
    path('api/messages/', views.message_list, name='message-list'),
    path('chatMessageSubmit/<int:sender>/<int:receiver>/',
         views.chatMessageSubmit, name='chatSubmit'),

    ########### volunteer chat Related ##########
    path('volunteerChat/<str:pk>/',
         views.volunteer_chat_view, name='volunteerChats'),
    path('volunteerChatMessage/<str:sender>/<str:receiver>/<str:pk>/',
         views.volunteer_message_view, name='volunteerChat'),

]

prj_wagntails/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_wagntails.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "prj_wagntails.views.error_404"
handler500 = 'prj_wagntails.views.error_500'
handler403 = 'prj_wagntails.views.error_403'
handler400 = 'prj_wagntails.views.error_400'

app_wagntails/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from django.db import models
from django.db.models.deletion import RESTRICT
from django_countries.fields import CountryField
import random

# Create your models here.

DAYS = (
    ('Sunday', 'Sunday'),
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
)

GENDER = (
    ('MALE', 'MALE'),
    ('FEMALE', 'FEMALE'),
    ('OTHER', 'OTHER'),
)

STATES = (
    ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'),
    ('Arunachal Pradesh', 'Arunachal Pradesh'),
    ('Assam', 'Assam'),
    ('Andhra Pradesh', 'Andhra Pradesh'),
    ('Bihar', 'Bihar'),
    ('Chandigarh', 'Chandigarh'),
    ('Chhattisgarh', 'Chhattisgarh'),
    ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'),
    ('Daman and Diu', 'Daman and Diu'),
    ('Delhi', 'Delhi'),
    ('Goa', 'Goa'),
    ('Gujarat', 'Gujarat'),
    ('Haryana', 'Haryana'),
    ('Himachal Pradesh', 'Himachal Pradesh'),
    ('Jammu and Kashmir', 'Jammu and Kashmir'),
    ('Jharkhand', 'Jharkhand'),
    ('Karnataka', 'Karnataka'),
    ('Kerala', 'Kerala'),
    ('Lakshadweep', 'Lakshadweep'),
    ('Madhya Pradesh', 'Madhya Pradesh'),
    ('Maharashtra', 'Maharashtra'),
    ('Manipur', 'Manipur'),
    ('Meghalaya', 'Meghalaya'),
    ('Mizoram', 'Mizoram'),
    ('Nagaland', 'Nagaland'),
    ('Orissa', 'Orissa'),
    ('Pondicherry', 'Pondicherry'),
    ('Punjab', 'Punjab'),
    ('Rajasthan', 'Rajasthan'),
    ('Sikkim', 'Sikkim'),
    ('Tamil Nadu', 'Tamil Nadu'),
    ('Tripura', 'Tripura'),
    ('Uttaranchal', 'Uttaranchal'),
    ('Uttar Pradesh', 'Uttar Pradesh'),
    ('West Bengal', 'West Bengal'),
)

TIME_PREFERENCE = (
    ('4a.m. - 5a.m.', '4a.m. - 5a.m.'),
    ('5a.m. - 6a.m.', '5a.m. - 6a.m.'),
    ('6a.m. - 7a.m.', '6a.m. - 7a.m.'),
    ('7p.m. - 8p.m.', '7p.m. - 8p.m.'),
    ('8p.m. - 9p.m.', '8p.m. - 9p.m.'),
    ('9p.m. - 10p.m.', '9p.m. - 10p.m.'),
)

STATUS = (
    ('At Home', 'At Home'),
    ('Sheltered', 'Sheltered'),
    ('ForWalk', 'ForWalk'),
)

BREED = (
    ('Labrador', 'Labrador'),
    ('Huskey', 'Huskey'),
    ('GrateDane', 'GrateDane'),
)


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    profile_pic = models.ImageField(default="profile1.png", null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    CATEGORY = (
        ('Indoor', 'Indoor'),
        ('Out Door', 'Out Door'),
    )

    name = models.CharField(max_length=200, null=True)
    price = models.FloatField(null=True)
    category = models.CharField(max_length=200, null=True, choices=CATEGORY)
    description = models.CharField(max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name


class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Out for delivery', 'Out for delivery'),
        ('Delivered', 'Delivered'),
    )

    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)
    note = models.CharField(max_length=1000, null=True)

    def __str__(self):
        return self.product.name


class Owner(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True, unique=True)
    profile_pic = models.ImageField(default="profile1.png", null=True, blank=True)
    aadhaar = models.PositiveIntegerField(validators=[MaxValueValidator(999999999999)], unique=True,default=random.randint(0,99999999999))
    address = models.CharField(max_length=500, null=True)
    city = models.CharField(max_length=100, null=True)
    state = models.CharField(max_length=100, null=True, choices=STATES)
    postal_code = models.PositiveIntegerField(validators=[MaxValueValidator(999999)],default=000000)
    is_owner = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Dog(models.Model):
    owner = models.ForeignKey(Owner, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=200, null=False)
    breed = models.CharField(max_length=200, null=True, choices=BREED)
    year = models.DateTimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)
    city = models.CharField(max_length=100, null=True)
    note = models.CharField(max_length=1000, null=True)
    gender = models.CharField(max_length=200, null=True, choices=GENDER)
    profile_pic = models.ImageField(default="logo.jpeg", null=True, blank=True)

    def __str__(self):
        return self.name


class Volunteer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    gender = models.CharField(max_length=20, null=True, choices=GENDER)
    age = models.PositiveIntegerField(validators=[MaxValueValidator(60)],default=18)
    phone = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, null=True, unique=True)
    aadhaar = models.PositiveIntegerField(validators=[MaxValueValidator(999999999999)], unique=True,default=random.randint(0,99999999999))
    address = models.CharField(max_length=500, null=True)
    city = models.CharField(max_length=100, null=True)
    state = models.CharField(max_length=100, null=True, choices=STATES)
    postal_code = models.PositiveIntegerField(validators=[MaxValueValidator(999999)],default=000000)
    day_pref = models.CharField(max_length=10, null=True, choices=DAYS)
    time_pref = models.CharField(max_length=20, null=True, choices=TIME_PREFERENCE)
    profile_pic = models.ImageField(default="profile1.png", null=True, blank=True)
    is_volunteer = models.BooleanField(default=True)
    dogs = models.ManyToManyField(Dog)

    def __str__(self):
        return self.name


class DateLocation(models.Model):
    name = models.CharField(max_length=30)
    street1 = models.CharField(max_length=90)
    street2 = models.CharField(max_length=90)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    country = CountryField()
    postal_code = models.PositiveIntegerField(validators=[MaxValueValidator(999999)],default=000000)
    
    def __str__(self):
        return self.name


class PlayDate(models.Model):
    playDate = models.DateField()
    location = models.ForeignKey(DateLocation, on_delete=RESTRICT)
    owner1 = models.ForeignKey(Owner, related_name='%(class)s_owner1', on_delete=RESTRICT)
    owner2 = models.ForeignKey(Owner, related_name='%(class)s_owner2', on_delete=RESTRICT)
    pet1 = models.ForeignKey(Dog, related_name='%(class)s_pet1', on_delete=RESTRICT)
    pet2 = models.ForeignKey(Dog, related_name='%(class)s_pet2', on_delete=RESTRICT)
    
    def __str__(self):
        return self.owner1.name + self.owner2.name + self.pet1.name + self.pet2.name + self.playDate

   
class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    # class Meta:
    #     ordering = ('timestamp',)

app_wagntails/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db.models import fields
from django.forms import ModelForm
from django.db import models
from .models import *


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class OwnerForm(ModelForm):
    class Meta:
        model = Owner
        fields = '__all__'
        exclude = ['user']


class DogForm(ModelForm):
    class Meta:
        model = Dog
        fields = '__all__'

class DogUpdateForm(ModelForm):
    class Meta:
        model = Dog
        fields = '__all__'
        exclude = ['owner']

class VolunteerForm(ModelForm):
    class Meta:
        model = Volunteer
        fields = '__all__'
        exclude = ['user', 'dogs']


class CustomMMCF(forms.ModelMultipleChoiceField):

    def label_from_instance(self, member):
        return member.name


class VolunteerDogForm(ModelForm):
    class Meta:
        model = Volunteer
        fields = ['name', 'dogs']

    city = models.CharField(max_length=30)
    dogs = CustomMMCF(
        queryset=Dog.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

class DateLocationForm(ModelForm):
    class Meta:
        model = DateLocation
        fields = '__all__'


class PlayDateForm(ModelForm):
    class Meta:
        model = PlayDate
        fields = ['playDate','location','owner2','pet1','pet2']
        exclude = ['owner1']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['location'].queryset = DateLocation.objects.all()
        self.fields['owner2'].queryset = Owner.objects.none()
        self.fields['pet1'].queryset = Dog.objects.none()
        self.fields['pet2'].queryset = Dog.objects.none()

class chatMessageForm(ModelForm):
    class Meta:
        model = Message
        fields = '__all__'
        # widgets = {'sender': forms.HiddenInput()}
        # widgets = {'receiver': forms.HiddenInput()}
        exclude = ['timestamp','is_read']

app_wagntails/templates/app_wagntails/1MainPageWT.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <style>
    </style>
    <link rel="stylesheet" href="{%static '/css/1MainPageWT.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>FrontMain</title>
</head>

<body>
<section class="banner">
    <div class="box content">
        <header>
            <img src="{%static '/images/logo.jpeg' %}" alt="Flowers in Chania" width="40" height="40" class="logo">
            <!-- <a href="#" class="logo">dogncat</a> -->
            <ul>
                <li><a href="SignupPM" target="_blank">Pet's Match</a></li>
                <li><a href="SignupV" target="_blank">Pet's Daycare</a></li>
            </ul>
        </header>

        <div class="contentBox">
            <h2>WAGGIN' TAILS</h2>
            <p> egestas vitae scelligula venenatis dolor. ultrices nec congue eget,
                ligula venenatis dolor. Maecenas nisl est, ultrices nec congue eget,
                auctor vitae massa. Fusce luctus vestibulum augue ut aliquet.
                <span id="dots">...</span><span id="more">erisque enim
            Nunc sagittis dictum nisi, sed ullamcorper ipsum dignissim ac. In at libero
            sed nunc venenatis imperdiet sed ornare turpis. Donec vitae dui eget tellus
            gravida venenatis. Integer fringilla congue eros non fermentum. Sed dapibus
            pulvinar nibh tempor porta.</span>
            </p>
            <button onclick="myFunction()" id="myBtn">Read more</button>
        </div>
        <ul class="sci">


            <h3>Contact Us</h3>

            <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-whatsapp" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a></li>
            <br>

        </ul>
        <!-- <div class="bottom">
            <p>Copyright © 2021 <a href="#">Waggin'Tails</a> All rights reserved</p>
        </div> -->
    </div>
    <div class="box images">
        <div class="imgBx">
            <img src="{%static '/images/Copy of Brown Geometric Flower Bloom Beauty Logo.png' %}" alt="1">
        </div>
        <div class="imgBx">
            <img src="{%static '/images/Copy of Black Geometric Flower Bloom Beauty Logo.png' %}" alt="2">
        </div>
        <div class="imgBx">
            <img src="{%static '/images/problematic.png' %}" alt="3">
            <!-- <a href="#" class="btn">Volunteer Login</a> -->
            <div class="bottom">
                <p>Copyright © 2021 <a href="#">Waggin'Tails</a> All rights reserved</p>
            </div>
        </div>

    </div>
</section>

<script>
    function myFunction() {
      var dots = document.getElementById("dots");
      var moreText = document.getElementById("more");
      var btnText = document.getElementById("myBtn");

      if (dots.style.display === "none") {
        dots.style.display = "inline";
        btnText.innerHTML = "Read more";
        moreText.style.display = "none";
      } else {
        dots.style.display = "none";
        btnText.innerHTML = "Read less";
        moreText.style.display = "inline";
      }
    }


</script>

</body>

</html>

app_wagntails/templates/app_wagntails/chatOld.html
{% extends 'app_wagntails/base.html' %}
{% block body %}
<div class="section" style="height: 80vh">
    <div class="row">
        <div class="col s3">
            <div class="card">
                <div class="collection">
                    {% for user in users %}
                    <a href="{% url 'chat' request.user.id user.id %}" id="user{{ user.id }}"
                        class="collection-item row">
                        <img src="https://frontend-1.adjust.com/new-assets/images/site-images/interface/user.svg"
                            class="col s4">
                        <div class="col s8">
                            <span class="title" style="font-weight: bolder">{{ user.username }}</span>
                        </div>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col s9">
            <div class="card">
                <div id="board" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll">
                    {% block messages %}

                    {% endblock %}
                </div>
                <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col s11">
                            <div class="input-field">
                                <input id="id_message" name="message" type="text" placeholder="Type your message..">
                            </div>
                        </div>
                        <div class="col s1" style="line-height: 80px">
                            <button class="btn btn-floating blue lighten-2 waves-effect waves-light"><i
                                    class="material-icons">send</i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% load static %}
<script src="{% static 'js/app_wagntails.js' %}"></script>
<script>
    // For receiving
    sender_id = "{{ receiver.id }}";
    receiver_id = "{{ request.user.id }}";

    //For sending
    $(function () {
        scrolltoend();
        $('#chat-box').on('submit', function (event) {
            event.preventDefault();
            var message = $('#id_message');
            send('{{ request.user.username }}', '{{ receiver.username }}', message.val());
            message.val('');
        })
    })
</script>
{% endblock %}

app_wagntails/templates/app_wagntails/dashboard.html
{%  extends 'app_wagntails/main.html' %}

{% block content %}

{%  include 'app_wagntails/status.html' %}

<br>

<div class="row">
    <div class="col-md-5">
        <h5>CUSTOMERS:</h5>
        <hr>
        <div class="card card-body">
            <a class="btn btn-primary  btn-sm btn-block" href="">Create Owner</a>
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>Owner</th>
                    <th>Phone</th>
                </tr>

                {% for customer in customers %}
                <tr>
                    <td><a class="btn btn-sm btn-info" href="{% url 'customer' customer.id %}">View</a></td>
                    <td>{{customer.name}}</td>
                    <td>{{customer.phone}}</td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>

    <div class="col-md-7">
        <h5>LAST 5 ORDERS</h5>
        <hr>
        <div class="card card-body">

            <table class="table table-sm">
                <tr>
                    <th>Product</th>
                    <th>Date Orderd</th>
                    <th>Status</th>
                    <th>Update</th>
                    <th>Remove</th>
                </tr>

                {% for order in orders %}
                <tr>
                    <td>{{order.product}}</td>
                    <td>{{order.date_created}}</td>
                    <td>{{order.status}}</td>
                    <td><a class="btn btn-sm btn-info" href="{% url 'update_order' order.id %}">Update</a></td>

                    <td><a class="btn btn-sm btn-danger" href="{% url 'delete_order' order.id %}">Delete</a></td>

                </tr>
                {% endfor %}


            </table>
        </div>
    </div>

</div>

{% endblock %}

app_wagntails/templates/app_wagntails/date_location_delete.html
{%  extends 'app_wagntails/base.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">


            <p>Are you sure you want to delete Location: "{{datelocation.name}}"?</p>

            <form action="{% url 'delete-location' datelocation.id owner.id %}" method="POST">

                {% csrf_token %}
                <a class="btn btn-warning" href="{% url 'home' %}">Cancel</a>

                <input class="btn btn-danger" type="submit" name="Confirm">
            </form>
        </div>
    </div>
</div>

{% endblock %}

app_wagntails/templates/app_wagntails/error.html
{% extends 'app_wagntails/base.html' %} {% load static %} {% block content %}

<br />
<div class="row">
  <div class="col-md-6">
    <div class="card card-body">
      <p>Error Page!!!</p>
      <br />
      <p>{{ request }}</p>
    </div>
  </div>
</div>

{% for field in form %}
<tr>
  <td>{{field}}</td>
</tr>
{% endfor %} {% if form.errors %}
<div class="alert alert-danger" role="alert">
  {% for field, errors in form.errors.items %} {% for error in errors %}
  <b>{{ field }}</b>: {{ error }} {% endfor %} {% endfor %}
</div>
{% endif %} {% if form.subject.errors %}
<ol>
  {% for error in form.subject.errors %}
  <li><strong>{{ error|escape }}</strong></li>
  {% endfor %}
</ol>
{% endif %} 

{% for field in form %}
<div class="fieldWrapper">
  {{ field.errors }} {{ field.label_tag }} {{ field }} {% if field.help_text %}
  <p class="help">{{ field.help_text|safe }}</p>
  {% endif %}
</div>
{% endfor %} 
{% endblock %}

app_wagntails/templates/app_wagntails/navigation.html
<!-- NOT IMPLEMENTED -->

app_wagntails/templates/app_wagntails/owner_status.html
<br>

<div class="row">
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="total-dogs">
                <div class="card-header">
                    <h5 class="card-title">Total Dogs</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{total_dogs}}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="orders-sheltered">
                <div class="card-header">
                    <h5 class="card-title">Dogs Sheltered</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{sheltered}}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="dogs-forwalk">
                <div class="card-header">
                    <h5 class="card-title">Dogs For Walk</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{forwalk}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>

app_wagntails/templates/app_wagntails/scripts.html
<!-- Required Js -->
{% load static %}

<script src="{% static 'js/vendor-all.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/pcoded.min.js' %}"></script>

app_wagntails/templates/app_wagntails/volunteer.html
{% extends 'app_wagntails/volunteer_main.html' %}

{% block content %}

<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Volunteer:{{volunteer.email}}</h5>
            <hr>
            <a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'accountVolunteer' %}">Update Volunteer</a>
            <a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'associateVolunteer' volunteer.id %}">View
                Dogs</a>

        </div>
    </div>

    <div class="col-md">
        <div class="card card-body">
            <h5>Contact Information</h5>
            <hr>
            <p>Email: {{volunteer.email}}</p>
            <p>Phone: {{volunteer.phone}}</p>
        </div>
    </div>
</div>


<br>
<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Dog</th>
                    <th>Breed</th>
                    <th>Status</th>
                    <th>Note</th>

                </tr>

                {% for dog in dogs %}
                <tr>
                    <td>{{dog.name}}</td>
                    <td>{{dog.breed}}</td>
                    <td>{{dog.status}}</td>
                    <td>{{dog.note}}</td>

                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>

{% endblock %}

app_wagntails/templates/app_wagntails/volunteer_status.html
<br>

<div class="row">
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="total-dogs">
                <div class="card-header">
                    <h5 class="card-title">Total Dogs</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{total_dogs}}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="orders-sheltered">
                <div class="card-header">
                    <h5 class="card-title">Dogs Sheltered</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{sheltered}}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="dogs-forwalk">
                <div class="card-header">
                    <h5 class="card-title">Dogs For Walk</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{forwalk}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>